//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.Subtract2NumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Subtract2NumbersReference.TwoNumberSubSoap")]
    public interface TwoNumberSubSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse SubtractTwoNumbers(Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Subtract2NumbersReference.SubtractTwoNumbersRequestBody Body;
        
        public SubtractTwoNumbersRequest() {
        }
        
        public SubtractTwoNumbersRequest(Clients.Subtract2NumbersReference.SubtractTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        public SubtractTwoNumbersRequestBody() {
        }
        
        public SubtractTwoNumbersRequestBody(string tal1, string tal2) {
            this.tal1 = tal1;
            this.tal2 = tal2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Subtract2NumbersReference.SubtractTwoNumbersResponseBody Body;
        
        public SubtractTwoNumbersResponse() {
        }
        
        public SubtractTwoNumbersResponse(Clients.Subtract2NumbersReference.SubtractTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubtractTwoNumbersResult;
        
        public SubtractTwoNumbersResponseBody() {
        }
        
        public SubtractTwoNumbersResponseBody(string SubtractTwoNumbersResult) {
            this.SubtractTwoNumbersResult = SubtractTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TwoNumberSubSoapChannel : Clients.Subtract2NumbersReference.TwoNumberSubSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoNumberSubSoapClient : System.ServiceModel.ClientBase<Clients.Subtract2NumbersReference.TwoNumberSubSoap>, Clients.Subtract2NumbersReference.TwoNumberSubSoap {
        
        public TwoNumberSubSoapClient() {
        }
        
        public TwoNumberSubSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoNumberSubSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberSubSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberSubSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse Clients.Subtract2NumbersReference.TwoNumberSubSoap.SubtractTwoNumbers(Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbers(request);
        }
        
        public string SubtractTwoNumbers(string tal1, string tal2) {
            Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest inValue = new Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest();
            inValue.Body = new Clients.Subtract2NumbersReference.SubtractTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse retVal = ((Clients.Subtract2NumbersReference.TwoNumberSubSoap)(this)).SubtractTwoNumbers(inValue);
            return retVal.Body.SubtractTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse> Clients.Subtract2NumbersReference.TwoNumberSubSoap.SubtractTwoNumbersAsync(Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.Subtract2NumbersReference.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(string tal1, string tal2) {
            Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest inValue = new Clients.Subtract2NumbersReference.SubtractTwoNumbersRequest();
            inValue.Body = new Clients.Subtract2NumbersReference.SubtractTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            return ((Clients.Subtract2NumbersReference.TwoNumberSubSoap)(this)).SubtractTwoNumbersAsync(inValue);
        }
    }
}
