//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.MiyazakiReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiyazakiReference.HayaoMiyazakiMoviesSoap")]
    public interface HayaoMiyazakiMoviesSoap {
        
        // CODEGEN: Generating message contract since element name inputYear from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteYearReturnMovie", ReplyAction="*")]
        Clients.MiyazakiReference.WriteYearReturnMovieResponse WriteYearReturnMovie(Clients.MiyazakiReference.WriteYearReturnMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteYearReturnMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.MiyazakiReference.WriteYearReturnMovieResponse> WriteYearReturnMovieAsync(Clients.MiyazakiReference.WriteYearReturnMovieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteYearReturnMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteYearReturnMovie", Namespace="http://tempuri.org/", Order=0)]
        public Clients.MiyazakiReference.WriteYearReturnMovieRequestBody Body;
        
        public WriteYearReturnMovieRequest() {
        }
        
        public WriteYearReturnMovieRequest(Clients.MiyazakiReference.WriteYearReturnMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteYearReturnMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputYear;
        
        public WriteYearReturnMovieRequestBody() {
        }
        
        public WriteYearReturnMovieRequestBody(string inputYear) {
            this.inputYear = inputYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteYearReturnMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteYearReturnMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.MiyazakiReference.WriteYearReturnMovieResponseBody Body;
        
        public WriteYearReturnMovieResponse() {
        }
        
        public WriteYearReturnMovieResponse(Clients.MiyazakiReference.WriteYearReturnMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteYearReturnMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WriteYearReturnMovieResult;
        
        public WriteYearReturnMovieResponseBody() {
        }
        
        public WriteYearReturnMovieResponseBody(string WriteYearReturnMovieResult) {
            this.WriteYearReturnMovieResult = WriteYearReturnMovieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HayaoMiyazakiMoviesSoapChannel : Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HayaoMiyazakiMoviesSoapClient : System.ServiceModel.ClientBase<Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap>, Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap {
        
        public HayaoMiyazakiMoviesSoapClient() {
        }
        
        public HayaoMiyazakiMoviesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HayaoMiyazakiMoviesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HayaoMiyazakiMoviesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HayaoMiyazakiMoviesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.MiyazakiReference.WriteYearReturnMovieResponse Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap.WriteYearReturnMovie(Clients.MiyazakiReference.WriteYearReturnMovieRequest request) {
            return base.Channel.WriteYearReturnMovie(request);
        }
        
        public string WriteYearReturnMovie(string inputYear) {
            Clients.MiyazakiReference.WriteYearReturnMovieRequest inValue = new Clients.MiyazakiReference.WriteYearReturnMovieRequest();
            inValue.Body = new Clients.MiyazakiReference.WriteYearReturnMovieRequestBody();
            inValue.Body.inputYear = inputYear;
            Clients.MiyazakiReference.WriteYearReturnMovieResponse retVal = ((Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap)(this)).WriteYearReturnMovie(inValue);
            return retVal.Body.WriteYearReturnMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.MiyazakiReference.WriteYearReturnMovieResponse> Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap.WriteYearReturnMovieAsync(Clients.MiyazakiReference.WriteYearReturnMovieRequest request) {
            return base.Channel.WriteYearReturnMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.MiyazakiReference.WriteYearReturnMovieResponse> WriteYearReturnMovieAsync(string inputYear) {
            Clients.MiyazakiReference.WriteYearReturnMovieRequest inValue = new Clients.MiyazakiReference.WriteYearReturnMovieRequest();
            inValue.Body = new Clients.MiyazakiReference.WriteYearReturnMovieRequestBody();
            inValue.Body.inputYear = inputYear;
            return ((Clients.MiyazakiReference.HayaoMiyazakiMoviesSoap)(this)).WriteYearReturnMovieAsync(inValue);
        }
    }
}
