//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForm.WeatherReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherReference.WeatherSoap")]
    public interface WeatherSoap {
        
        // CODEGEN: Generating message contract since element name WheatherForecastResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WheatherForecast", ReplyAction="*")]
        WeatherForm.WeatherReference.WheatherForecastResponse WheatherForecast(WeatherForm.WeatherReference.WheatherForecastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WheatherForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherForm.WeatherReference.WheatherForecastResponse> WheatherForecastAsync(WeatherForm.WeatherReference.WheatherForecastRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WheatherForecastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WheatherForecast", Namespace="http://tempuri.org/", Order=0)]
        public WeatherForm.WeatherReference.WheatherForecastRequestBody Body;
        
        public WheatherForecastRequest() {
        }
        
        public WheatherForecastRequest(WeatherForm.WeatherReference.WheatherForecastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WheatherForecastRequestBody {
        
        public WheatherForecastRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WheatherForecastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WheatherForecastResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeatherForm.WeatherReference.WheatherForecastResponseBody Body;
        
        public WheatherForecastResponse() {
        }
        
        public WheatherForecastResponse(WeatherForm.WeatherReference.WheatherForecastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WheatherForecastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WheatherForecastResult;
        
        public WheatherForecastResponseBody() {
        }
        
        public WheatherForecastResponseBody(string WheatherForecastResult) {
            this.WheatherForecastResult = WheatherForecastResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherSoapChannel : WeatherForm.WeatherReference.WeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherSoapClient : System.ServiceModel.ClientBase<WeatherForm.WeatherReference.WeatherSoap>, WeatherForm.WeatherReference.WeatherSoap {
        
        public WeatherSoapClient() {
        }
        
        public WeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherForm.WeatherReference.WheatherForecastResponse WeatherForm.WeatherReference.WeatherSoap.WheatherForecast(WeatherForm.WeatherReference.WheatherForecastRequest request) {
            return base.Channel.WheatherForecast(request);
        }
        
        public string WheatherForecast() {
            WeatherForm.WeatherReference.WheatherForecastRequest inValue = new WeatherForm.WeatherReference.WheatherForecastRequest();
            inValue.Body = new WeatherForm.WeatherReference.WheatherForecastRequestBody();
            WeatherForm.WeatherReference.WheatherForecastResponse retVal = ((WeatherForm.WeatherReference.WeatherSoap)(this)).WheatherForecast(inValue);
            return retVal.Body.WheatherForecastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherForm.WeatherReference.WheatherForecastResponse> WeatherForm.WeatherReference.WeatherSoap.WheatherForecastAsync(WeatherForm.WeatherReference.WheatherForecastRequest request) {
            return base.Channel.WheatherForecastAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherForm.WeatherReference.WheatherForecastResponse> WheatherForecastAsync() {
            WeatherForm.WeatherReference.WheatherForecastRequest inValue = new WeatherForm.WeatherReference.WheatherForecastRequest();
            inValue.Body = new WeatherForm.WeatherReference.WheatherForecastRequestBody();
            return ((WeatherForm.WeatherReference.WeatherSoap)(this)).WheatherForecastAsync(inValue);
        }
    }
}
