//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForm.AddTwoNumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddTwoNumbersReference.TwoNumberAddSoap")]
    public interface TwoNumberAddSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse AddTwoNumbers(WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse> AddTwoNumbersAsync(WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequestBody Body;
        
        public AddTwoNumbersRequest() {
        }
        
        public AddTwoNumbersRequest(WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        public AddTwoNumbersRequestBody() {
        }
        
        public AddTwoNumbersRequestBody(string tal1, string tal2) {
            this.tal1 = tal1;
            this.tal2 = tal2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponseBody Body;
        
        public AddTwoNumbersResponse() {
        }
        
        public AddTwoNumbersResponse(WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoNumbersResult;
        
        public AddTwoNumbersResponseBody() {
        }
        
        public AddTwoNumbersResponseBody(string AddTwoNumbersResult) {
            this.AddTwoNumbersResult = AddTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TwoNumberAddSoapChannel : WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoNumberAddSoapClient : System.ServiceModel.ClientBase<WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap>, WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap {
        
        public TwoNumberAddSoapClient() {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberAddSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap.AddTwoNumbers(WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbers(request);
        }
        
        public string AddTwoNumbers(string tal1, string tal2) {
            WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest inValue = new WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest();
            inValue.Body = new WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse retVal = ((WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap)(this)).AddTwoNumbers(inValue);
            return retVal.Body.AddTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse> WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap.AddTwoNumbersAsync(WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherForm.AddTwoNumbersReference.AddTwoNumbersResponse> AddTwoNumbersAsync(string tal1, string tal2) {
            WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest inValue = new WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequest();
            inValue.Body = new WeatherForm.AddTwoNumbersReference.AddTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            return ((WeatherForm.AddTwoNumbersReference.TwoNumberAddSoap)(this)).AddTwoNumbersAsync(inValue);
        }
    }
}
