//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.Add3NumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Add3NumbersReference.ThreeNumberAddSoap")]
    public interface ThreeNumberAddSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        Clients.Add3NumbersReference.AddThreeNumbersResponse AddThreeNumbers(Clients.Add3NumbersReference.AddThreeNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.Add3NumbersReference.AddThreeNumbersResponse> AddThreeNumbersAsync(Clients.Add3NumbersReference.AddThreeNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Add3NumbersReference.AddThreeNumbersRequestBody Body;
        
        public AddThreeNumbersRequest() {
        }
        
        public AddThreeNumbersRequest(Clients.Add3NumbersReference.AddThreeNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tal3;
        
        public AddThreeNumbersRequestBody() {
        }
        
        public AddThreeNumbersRequestBody(string tal1, string tal2, string tal3) {
            this.tal1 = tal1;
            this.tal2 = tal2;
            this.tal3 = tal3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Add3NumbersReference.AddThreeNumbersResponseBody Body;
        
        public AddThreeNumbersResponse() {
        }
        
        public AddThreeNumbersResponse(Clients.Add3NumbersReference.AddThreeNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddThreeNumbersResult;
        
        public AddThreeNumbersResponseBody() {
        }
        
        public AddThreeNumbersResponseBody(string AddThreeNumbersResult) {
            this.AddThreeNumbersResult = AddThreeNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThreeNumberAddSoapChannel : Clients.Add3NumbersReference.ThreeNumberAddSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThreeNumberAddSoapClient : System.ServiceModel.ClientBase<Clients.Add3NumbersReference.ThreeNumberAddSoap>, Clients.Add3NumbersReference.ThreeNumberAddSoap {
        
        public ThreeNumberAddSoapClient() {
        }
        
        public ThreeNumberAddSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThreeNumberAddSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreeNumberAddSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreeNumberAddSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.Add3NumbersReference.AddThreeNumbersResponse Clients.Add3NumbersReference.ThreeNumberAddSoap.AddThreeNumbers(Clients.Add3NumbersReference.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbers(request);
        }
        
        public string AddThreeNumbers(string tal1, string tal2, string tal3) {
            Clients.Add3NumbersReference.AddThreeNumbersRequest inValue = new Clients.Add3NumbersReference.AddThreeNumbersRequest();
            inValue.Body = new Clients.Add3NumbersReference.AddThreeNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            inValue.Body.tal3 = tal3;
            Clients.Add3NumbersReference.AddThreeNumbersResponse retVal = ((Clients.Add3NumbersReference.ThreeNumberAddSoap)(this)).AddThreeNumbers(inValue);
            return retVal.Body.AddThreeNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.Add3NumbersReference.AddThreeNumbersResponse> Clients.Add3NumbersReference.ThreeNumberAddSoap.AddThreeNumbersAsync(Clients.Add3NumbersReference.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.Add3NumbersReference.AddThreeNumbersResponse> AddThreeNumbersAsync(string tal1, string tal2, string tal3) {
            Clients.Add3NumbersReference.AddThreeNumbersRequest inValue = new Clients.Add3NumbersReference.AddThreeNumbersRequest();
            inValue.Body = new Clients.Add3NumbersReference.AddThreeNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            inValue.Body.tal3 = tal3;
            return ((Clients.Add3NumbersReference.ThreeNumberAddSoap)(this)).AddThreeNumbersAsync(inValue);
        }
    }
}
