//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.Add2NumbersReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Add2NumbersReference.TwoNumberAddSoap")]
    public interface TwoNumberAddSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        Clients.Add2NumbersReference.AddTwoNumbersResponse AddTwoNumbers(Clients.Add2NumbersReference.AddTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.Add2NumbersReference.AddTwoNumbersResponse> AddTwoNumbersAsync(Clients.Add2NumbersReference.AddTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Add2NumbersReference.AddTwoNumbersRequestBody Body;
        
        public AddTwoNumbersRequest() {
        }
        
        public AddTwoNumbersRequest(Clients.Add2NumbersReference.AddTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        public AddTwoNumbersRequestBody() {
        }
        
        public AddTwoNumbersRequestBody(string tal1, string tal2) {
            this.tal1 = tal1;
            this.tal2 = tal2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.Add2NumbersReference.AddTwoNumbersResponseBody Body;
        
        public AddTwoNumbersResponse() {
        }
        
        public AddTwoNumbersResponse(Clients.Add2NumbersReference.AddTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoNumbersResult;
        
        public AddTwoNumbersResponseBody() {
        }
        
        public AddTwoNumbersResponseBody(string AddTwoNumbersResult) {
            this.AddTwoNumbersResult = AddTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TwoNumberAddSoapChannel : Clients.Add2NumbersReference.TwoNumberAddSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoNumberAddSoapClient : System.ServiceModel.ClientBase<Clients.Add2NumbersReference.TwoNumberAddSoap>, Clients.Add2NumbersReference.TwoNumberAddSoap {
        
        public TwoNumberAddSoapClient() {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberAddSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoNumberAddSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.Add2NumbersReference.AddTwoNumbersResponse Clients.Add2NumbersReference.TwoNumberAddSoap.AddTwoNumbers(Clients.Add2NumbersReference.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbers(request);
        }
        
        public string AddTwoNumbers(string tal1, string tal2) {
            Clients.Add2NumbersReference.AddTwoNumbersRequest inValue = new Clients.Add2NumbersReference.AddTwoNumbersRequest();
            inValue.Body = new Clients.Add2NumbersReference.AddTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            Clients.Add2NumbersReference.AddTwoNumbersResponse retVal = ((Clients.Add2NumbersReference.TwoNumberAddSoap)(this)).AddTwoNumbers(inValue);
            return retVal.Body.AddTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.Add2NumbersReference.AddTwoNumbersResponse> Clients.Add2NumbersReference.TwoNumberAddSoap.AddTwoNumbersAsync(Clients.Add2NumbersReference.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.Add2NumbersReference.AddTwoNumbersResponse> AddTwoNumbersAsync(string tal1, string tal2) {
            Clients.Add2NumbersReference.AddTwoNumbersRequest inValue = new Clients.Add2NumbersReference.AddTwoNumbersRequest();
            inValue.Body = new Clients.Add2NumbersReference.AddTwoNumbersRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            return ((Clients.Add2NumbersReference.TwoNumberAddSoap)(this)).AddTwoNumbersAsync(inValue);
        }
    }
}
