//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.RazzieReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RazzieReference.WorstMoviesSoap")]
    public interface WorstMoviesSoap {
        
        // CODEGEN: Generating message contract since element name inputYear from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputYearReturnWorstMovie", ReplyAction="*")]
        Clients.RazzieReference.InputYearReturnWorstMovieResponse InputYearReturnWorstMovie(Clients.RazzieReference.InputYearReturnWorstMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputYearReturnWorstMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Clients.RazzieReference.InputYearReturnWorstMovieResponse> InputYearReturnWorstMovieAsync(Clients.RazzieReference.InputYearReturnWorstMovieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InputYearReturnWorstMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InputYearReturnWorstMovie", Namespace="http://tempuri.org/", Order=0)]
        public Clients.RazzieReference.InputYearReturnWorstMovieRequestBody Body;
        
        public InputYearReturnWorstMovieRequest() {
        }
        
        public InputYearReturnWorstMovieRequest(Clients.RazzieReference.InputYearReturnWorstMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InputYearReturnWorstMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputYear;
        
        public InputYearReturnWorstMovieRequestBody() {
        }
        
        public InputYearReturnWorstMovieRequestBody(string inputYear) {
            this.inputYear = inputYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InputYearReturnWorstMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InputYearReturnWorstMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clients.RazzieReference.InputYearReturnWorstMovieResponseBody Body;
        
        public InputYearReturnWorstMovieResponse() {
        }
        
        public InputYearReturnWorstMovieResponse(Clients.RazzieReference.InputYearReturnWorstMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InputYearReturnWorstMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputYearReturnWorstMovieResult;
        
        public InputYearReturnWorstMovieResponseBody() {
        }
        
        public InputYearReturnWorstMovieResponseBody(string InputYearReturnWorstMovieResult) {
            this.InputYearReturnWorstMovieResult = InputYearReturnWorstMovieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorstMoviesSoapChannel : Clients.RazzieReference.WorstMoviesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorstMoviesSoapClient : System.ServiceModel.ClientBase<Clients.RazzieReference.WorstMoviesSoap>, Clients.RazzieReference.WorstMoviesSoap {
        
        public WorstMoviesSoapClient() {
        }
        
        public WorstMoviesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorstMoviesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorstMoviesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorstMoviesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clients.RazzieReference.InputYearReturnWorstMovieResponse Clients.RazzieReference.WorstMoviesSoap.InputYearReturnWorstMovie(Clients.RazzieReference.InputYearReturnWorstMovieRequest request) {
            return base.Channel.InputYearReturnWorstMovie(request);
        }
        
        public string InputYearReturnWorstMovie(string inputYear) {
            Clients.RazzieReference.InputYearReturnWorstMovieRequest inValue = new Clients.RazzieReference.InputYearReturnWorstMovieRequest();
            inValue.Body = new Clients.RazzieReference.InputYearReturnWorstMovieRequestBody();
            inValue.Body.inputYear = inputYear;
            Clients.RazzieReference.InputYearReturnWorstMovieResponse retVal = ((Clients.RazzieReference.WorstMoviesSoap)(this)).InputYearReturnWorstMovie(inValue);
            return retVal.Body.InputYearReturnWorstMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clients.RazzieReference.InputYearReturnWorstMovieResponse> Clients.RazzieReference.WorstMoviesSoap.InputYearReturnWorstMovieAsync(Clients.RazzieReference.InputYearReturnWorstMovieRequest request) {
            return base.Channel.InputYearReturnWorstMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clients.RazzieReference.InputYearReturnWorstMovieResponse> InputYearReturnWorstMovieAsync(string inputYear) {
            Clients.RazzieReference.InputYearReturnWorstMovieRequest inValue = new Clients.RazzieReference.InputYearReturnWorstMovieRequest();
            inValue.Body = new Clients.RazzieReference.InputYearReturnWorstMovieRequestBody();
            inValue.Body.inputYear = inputYear;
            return ((Clients.RazzieReference.WorstMoviesSoap)(this)).InputYearReturnWorstMovieAsync(inValue);
        }
    }
}
